### ISSUE TITLE
Proposiciones individual 

### ISSUE THREAD

**Issue by DiegoLV117** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-DiegoLV117#1]
[PRACTICA INDI PROPOSICIONES Diego E Lopez Vasquez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-DiegoLV117/files/13193675/PRACTICA.INDI.PROPOSICIONES.Diego.E.Lopez.Vasquez.pdf)

**Comment by DanAlejandr** [comment]
Portada: 25/25
Procedimiento: 22/25 (Falta descripción de resultados, lista de figuras).
Figuras, ilustraciones y fotografías: 0/25 (No contiene Figuras, Ilustraciones y Fotografías).
Resultados y Conclusión: 25/25
Total: 72/100

Puntaje final: 14.4/20
Calificado por el equipo de Mayra, Diego, Félix, Daniel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
